name: Stack

version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    image: api-image
    ports:
      - "8000:8000"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true" #epickaporownywarkabazwiedzyuczelni.rocks
      - "traefik.http.routers.app.rule=Host(`epickaporownywarkabazwiedzyuczelni.rocks`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
